// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/skiptaskrequest.proto

package com.netflix.conductor.proto;

public final class SkipTaskRequestPb {
  private SkipTaskRequestPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SkipTaskRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.SkipTaskRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */
    int getTaskInputCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */
    boolean containsTaskInput(
        java.lang.String key);
    /**
     * Use {@link #getTaskInputMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getTaskInput();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getTaskInputMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */

    com.google.protobuf.Value getTaskInputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */

    com.google.protobuf.Value getTaskInputOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */
    int getTaskOutputCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */
    boolean containsTaskOutput(
        java.lang.String key);
    /**
     * Use {@link #getTaskOutputMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getTaskOutput();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getTaskOutputMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */

    com.google.protobuf.Value getTaskOutputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */

    com.google.protobuf.Value getTaskOutputOrThrow(
        java.lang.String key);

    /**
     * <code>.google.protobuf.Any task_input_message = 3;</code>
     */
    boolean hasTaskInputMessage();
    /**
     * <code>.google.protobuf.Any task_input_message = 3;</code>
     */
    com.google.protobuf.Any getTaskInputMessage();
    /**
     * <code>.google.protobuf.Any task_input_message = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getTaskInputMessageOrBuilder();

    /**
     * <code>.google.protobuf.Any task_output_message = 4;</code>
     */
    boolean hasTaskOutputMessage();
    /**
     * <code>.google.protobuf.Any task_output_message = 4;</code>
     */
    com.google.protobuf.Any getTaskOutputMessage();
    /**
     * <code>.google.protobuf.Any task_output_message = 4;</code>
     */
    com.google.protobuf.AnyOrBuilder getTaskOutputMessageOrBuilder();
  }
  /**
   * Protobuf type {@code conductor.proto.SkipTaskRequest}
   */
  public  static final class SkipTaskRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.SkipTaskRequest)
      SkipTaskRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SkipTaskRequest.newBuilder() to construct.
    private SkipTaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SkipTaskRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SkipTaskRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                taskInput_ = com.google.protobuf.MapField.newMapField(
                    TaskInputDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              taskInput__ = input.readMessage(
                  TaskInputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              taskInput_.getMutableMap().put(
                  taskInput__.getKey(), taskInput__.getValue());
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                taskOutput_ = com.google.protobuf.MapField.newMapField(
                    TaskOutputDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              taskOutput__ = input.readMessage(
                  TaskOutputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              taskOutput_.getMutableMap().put(
                  taskOutput__.getKey(), taskOutput__.getValue());
              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (taskInputMessage_ != null) {
                subBuilder = taskInputMessage_.toBuilder();
              }
              taskInputMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(taskInputMessage_);
                taskInputMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (taskOutputMessage_ != null) {
                subBuilder = taskOutputMessage_.toBuilder();
              }
              taskOutputMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(taskOutputMessage_);
                taskOutputMessage_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetTaskInput();
        case 2:
          return internalGetTaskOutput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.class, com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TASK_INPUT_FIELD_NUMBER = 1;
    private static final class TaskInputDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_TaskInputEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> taskInput_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetTaskInput() {
      if (taskInput_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TaskInputDefaultEntryHolder.defaultEntry);
      }
      return taskInput_;
    }

    public int getTaskInputCount() {
      return internalGetTaskInput().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */

    public boolean containsTaskInput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTaskInput().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTaskInputMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskInput() {
      return getTaskInputMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskInputMap() {
      return internalGetTaskInput().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */

    public com.google.protobuf.Value getTaskInputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetTaskInput().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
     */

    public com.google.protobuf.Value getTaskInputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetTaskInput().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TASK_OUTPUT_FIELD_NUMBER = 2;
    private static final class TaskOutputDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_TaskOutputEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> taskOutput_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetTaskOutput() {
      if (taskOutput_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TaskOutputDefaultEntryHolder.defaultEntry);
      }
      return taskOutput_;
    }

    public int getTaskOutputCount() {
      return internalGetTaskOutput().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */

    public boolean containsTaskOutput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTaskOutput().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTaskOutputMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskOutput() {
      return getTaskOutputMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskOutputMap() {
      return internalGetTaskOutput().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */

    public com.google.protobuf.Value getTaskOutputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetTaskOutput().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
     */

    public com.google.protobuf.Value getTaskOutputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetTaskOutput().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TASK_INPUT_MESSAGE_FIELD_NUMBER = 3;
    private com.google.protobuf.Any taskInputMessage_;
    /**
     * <code>.google.protobuf.Any task_input_message = 3;</code>
     */
    public boolean hasTaskInputMessage() {
      return taskInputMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any task_input_message = 3;</code>
     */
    public com.google.protobuf.Any getTaskInputMessage() {
      return taskInputMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : taskInputMessage_;
    }
    /**
     * <code>.google.protobuf.Any task_input_message = 3;</code>
     */
    public com.google.protobuf.AnyOrBuilder getTaskInputMessageOrBuilder() {
      return getTaskInputMessage();
    }

    public static final int TASK_OUTPUT_MESSAGE_FIELD_NUMBER = 4;
    private com.google.protobuf.Any taskOutputMessage_;
    /**
     * <code>.google.protobuf.Any task_output_message = 4;</code>
     */
    public boolean hasTaskOutputMessage() {
      return taskOutputMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any task_output_message = 4;</code>
     */
    public com.google.protobuf.Any getTaskOutputMessage() {
      return taskOutputMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : taskOutputMessage_;
    }
    /**
     * <code>.google.protobuf.Any task_output_message = 4;</code>
     */
    public com.google.protobuf.AnyOrBuilder getTaskOutputMessageOrBuilder() {
      return getTaskOutputMessage();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTaskInput(),
          TaskInputDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTaskOutput(),
          TaskOutputDefaultEntryHolder.defaultEntry,
          2);
      if (taskInputMessage_ != null) {
        output.writeMessage(3, getTaskInputMessage());
      }
      if (taskOutputMessage_ != null) {
        output.writeMessage(4, getTaskOutputMessage());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetTaskInput().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        taskInput__ = TaskInputDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, taskInput__);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetTaskOutput().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        taskOutput__ = TaskOutputDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, taskOutput__);
      }
      if (taskInputMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTaskInputMessage());
      }
      if (taskOutputMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getTaskOutputMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest other = (com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest) obj;

      boolean result = true;
      result = result && internalGetTaskInput().equals(
          other.internalGetTaskInput());
      result = result && internalGetTaskOutput().equals(
          other.internalGetTaskOutput());
      result = result && (hasTaskInputMessage() == other.hasTaskInputMessage());
      if (hasTaskInputMessage()) {
        result = result && getTaskInputMessage()
            .equals(other.getTaskInputMessage());
      }
      result = result && (hasTaskOutputMessage() == other.hasTaskOutputMessage());
      if (hasTaskOutputMessage()) {
        result = result && getTaskOutputMessage()
            .equals(other.getTaskOutputMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetTaskInput().getMap().isEmpty()) {
        hash = (37 * hash) + TASK_INPUT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTaskInput().hashCode();
      }
      if (!internalGetTaskOutput().getMap().isEmpty()) {
        hash = (37 * hash) + TASK_OUTPUT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTaskOutput().hashCode();
      }
      if (hasTaskInputMessage()) {
        hash = (37 * hash) + TASK_INPUT_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getTaskInputMessage().hashCode();
      }
      if (hasTaskOutputMessage()) {
        hash = (37 * hash) + TASK_OUTPUT_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getTaskOutputMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.SkipTaskRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.SkipTaskRequest)
        com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetTaskInput();
          case 2:
            return internalGetTaskOutput();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableTaskInput();
          case 2:
            return internalGetMutableTaskOutput();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.class, com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableTaskInput().clear();
        internalGetMutableTaskOutput().clear();
        if (taskInputMessageBuilder_ == null) {
          taskInputMessage_ = null;
        } else {
          taskInputMessage_ = null;
          taskInputMessageBuilder_ = null;
        }
        if (taskOutputMessageBuilder_ == null) {
          taskOutputMessage_ = null;
        } else {
          taskOutputMessage_ = null;
          taskOutputMessageBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.SkipTaskRequestPb.internal_static_conductor_proto_SkipTaskRequest_descriptor;
      }

      public com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest getDefaultInstanceForType() {
        return com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.getDefaultInstance();
      }

      public com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest build() {
        com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest buildPartial() {
        com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest result = new com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.taskInput_ = internalGetTaskInput();
        result.taskInput_.makeImmutable();
        result.taskOutput_ = internalGetTaskOutput();
        result.taskOutput_.makeImmutable();
        if (taskInputMessageBuilder_ == null) {
          result.taskInputMessage_ = taskInputMessage_;
        } else {
          result.taskInputMessage_ = taskInputMessageBuilder_.build();
        }
        if (taskOutputMessageBuilder_ == null) {
          result.taskOutputMessage_ = taskOutputMessage_;
        } else {
          result.taskOutputMessage_ = taskOutputMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest) {
          return mergeFrom((com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest other) {
        if (other == com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest.getDefaultInstance()) return this;
        internalGetMutableTaskInput().mergeFrom(
            other.internalGetTaskInput());
        internalGetMutableTaskOutput().mergeFrom(
            other.internalGetTaskOutput());
        if (other.hasTaskInputMessage()) {
          mergeTaskInputMessage(other.getTaskInputMessage());
        }
        if (other.hasTaskOutputMessage()) {
          mergeTaskOutputMessage(other.getTaskOutputMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Value> taskInput_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetTaskInput() {
        if (taskInput_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TaskInputDefaultEntryHolder.defaultEntry);
        }
        return taskInput_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetMutableTaskInput() {
        onChanged();;
        if (taskInput_ == null) {
          taskInput_ = com.google.protobuf.MapField.newMapField(
              TaskInputDefaultEntryHolder.defaultEntry);
        }
        if (!taskInput_.isMutable()) {
          taskInput_ = taskInput_.copy();
        }
        return taskInput_;
      }

      public int getTaskInputCount() {
        return internalGetTaskInput().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */

      public boolean containsTaskInput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTaskInput().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTaskInputMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskInput() {
        return getTaskInputMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskInputMap() {
        return internalGetTaskInput().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */

      public com.google.protobuf.Value getTaskInputOrDefault(
          java.lang.String key,
          com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetTaskInput().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */

      public com.google.protobuf.Value getTaskInputOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetTaskInput().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTaskInput() {
        internalGetMutableTaskInput().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */

      public Builder removeTaskInput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskInput().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
      getMutableTaskInput() {
        return internalGetMutableTaskInput().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */
      public Builder putTaskInput(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskInput().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_input = 1;</code>
       */

      public Builder putAllTaskInput(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        internalGetMutableTaskInput().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Value> taskOutput_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetTaskOutput() {
        if (taskOutput_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TaskOutputDefaultEntryHolder.defaultEntry);
        }
        return taskOutput_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetMutableTaskOutput() {
        onChanged();;
        if (taskOutput_ == null) {
          taskOutput_ = com.google.protobuf.MapField.newMapField(
              TaskOutputDefaultEntryHolder.defaultEntry);
        }
        if (!taskOutput_.isMutable()) {
          taskOutput_ = taskOutput_.copy();
        }
        return taskOutput_;
      }

      public int getTaskOutputCount() {
        return internalGetTaskOutput().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */

      public boolean containsTaskOutput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTaskOutput().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTaskOutputMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskOutput() {
        return getTaskOutputMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.Value> getTaskOutputMap() {
        return internalGetTaskOutput().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */

      public com.google.protobuf.Value getTaskOutputOrDefault(
          java.lang.String key,
          com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetTaskOutput().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */

      public com.google.protobuf.Value getTaskOutputOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetTaskOutput().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTaskOutput() {
        internalGetMutableTaskOutput().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */

      public Builder removeTaskOutput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskOutput().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
      getMutableTaskOutput() {
        return internalGetMutableTaskOutput().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */
      public Builder putTaskOutput(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskOutput().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; task_output = 2;</code>
       */

      public Builder putAllTaskOutput(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        internalGetMutableTaskOutput().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.Any taskInputMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> taskInputMessageBuilder_;
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public boolean hasTaskInputMessage() {
        return taskInputMessageBuilder_ != null || taskInputMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public com.google.protobuf.Any getTaskInputMessage() {
        if (taskInputMessageBuilder_ == null) {
          return taskInputMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : taskInputMessage_;
        } else {
          return taskInputMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public Builder setTaskInputMessage(com.google.protobuf.Any value) {
        if (taskInputMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          taskInputMessage_ = value;
          onChanged();
        } else {
          taskInputMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public Builder setTaskInputMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (taskInputMessageBuilder_ == null) {
          taskInputMessage_ = builderForValue.build();
          onChanged();
        } else {
          taskInputMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public Builder mergeTaskInputMessage(com.google.protobuf.Any value) {
        if (taskInputMessageBuilder_ == null) {
          if (taskInputMessage_ != null) {
            taskInputMessage_ =
              com.google.protobuf.Any.newBuilder(taskInputMessage_).mergeFrom(value).buildPartial();
          } else {
            taskInputMessage_ = value;
          }
          onChanged();
        } else {
          taskInputMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public Builder clearTaskInputMessage() {
        if (taskInputMessageBuilder_ == null) {
          taskInputMessage_ = null;
          onChanged();
        } else {
          taskInputMessage_ = null;
          taskInputMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public com.google.protobuf.Any.Builder getTaskInputMessageBuilder() {
        
        onChanged();
        return getTaskInputMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getTaskInputMessageOrBuilder() {
        if (taskInputMessageBuilder_ != null) {
          return taskInputMessageBuilder_.getMessageOrBuilder();
        } else {
          return taskInputMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : taskInputMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any task_input_message = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getTaskInputMessageFieldBuilder() {
        if (taskInputMessageBuilder_ == null) {
          taskInputMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getTaskInputMessage(),
                  getParentForChildren(),
                  isClean());
          taskInputMessage_ = null;
        }
        return taskInputMessageBuilder_;
      }

      private com.google.protobuf.Any taskOutputMessage_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> taskOutputMessageBuilder_;
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public boolean hasTaskOutputMessage() {
        return taskOutputMessageBuilder_ != null || taskOutputMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public com.google.protobuf.Any getTaskOutputMessage() {
        if (taskOutputMessageBuilder_ == null) {
          return taskOutputMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : taskOutputMessage_;
        } else {
          return taskOutputMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public Builder setTaskOutputMessage(com.google.protobuf.Any value) {
        if (taskOutputMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          taskOutputMessage_ = value;
          onChanged();
        } else {
          taskOutputMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public Builder setTaskOutputMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (taskOutputMessageBuilder_ == null) {
          taskOutputMessage_ = builderForValue.build();
          onChanged();
        } else {
          taskOutputMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public Builder mergeTaskOutputMessage(com.google.protobuf.Any value) {
        if (taskOutputMessageBuilder_ == null) {
          if (taskOutputMessage_ != null) {
            taskOutputMessage_ =
              com.google.protobuf.Any.newBuilder(taskOutputMessage_).mergeFrom(value).buildPartial();
          } else {
            taskOutputMessage_ = value;
          }
          onChanged();
        } else {
          taskOutputMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public Builder clearTaskOutputMessage() {
        if (taskOutputMessageBuilder_ == null) {
          taskOutputMessage_ = null;
          onChanged();
        } else {
          taskOutputMessage_ = null;
          taskOutputMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public com.google.protobuf.Any.Builder getTaskOutputMessageBuilder() {
        
        onChanged();
        return getTaskOutputMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      public com.google.protobuf.AnyOrBuilder getTaskOutputMessageOrBuilder() {
        if (taskOutputMessageBuilder_ != null) {
          return taskOutputMessageBuilder_.getMessageOrBuilder();
        } else {
          return taskOutputMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : taskOutputMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any task_output_message = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getTaskOutputMessageFieldBuilder() {
        if (taskOutputMessageBuilder_ == null) {
          taskOutputMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getTaskOutputMessage(),
                  getParentForChildren(),
                  isClean());
          taskOutputMessage_ = null;
        }
        return taskOutputMessageBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.SkipTaskRequest)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.SkipTaskRequest)
    private static final com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest();
    }

    public static com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SkipTaskRequest>
        PARSER = new com.google.protobuf.AbstractParser<SkipTaskRequest>() {
      public SkipTaskRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SkipTaskRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SkipTaskRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SkipTaskRequest> getParserForType() {
      return PARSER;
    }

    public com.netflix.conductor.proto.SkipTaskRequestPb.SkipTaskRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_SkipTaskRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_SkipTaskRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_SkipTaskRequest_TaskInputEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_SkipTaskRequest_TaskInputEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_SkipTaskRequest_TaskOutputEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_SkipTaskRequest_TaskOutputEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033model/skiptaskrequest.proto\022\017conductor" +
      ".proto\032\034google/protobuf/struct.proto\032\031go" +
      "ogle/protobuf/any.proto\"\227\003\n\017SkipTaskRequ" +
      "est\022C\n\ntask_input\030\001 \003(\0132/.conductor.prot" +
      "o.SkipTaskRequest.TaskInputEntry\022E\n\013task" +
      "_output\030\002 \003(\01320.conductor.proto.SkipTask" +
      "Request.TaskOutputEntry\0220\n\022task_input_me" +
      "ssage\030\003 \001(\0132\024.google.protobuf.Any\0221\n\023tas" +
      "k_output_message\030\004 \001(\0132\024.google.protobuf" +
      ".Any\032H\n\016TaskInputEntry\022\013\n\003key\030\001 \001(\t\022%\n\005v" +
      "alue\030\002 \001(\0132\026.google.protobuf.Value:\0028\001\032I" +
      "\n\017TaskOutputEntry\022\013\n\003key\030\001 \001(\t\022%\n\005value\030" +
      "\002 \001(\0132\026.google.protobuf.Value:\0028\001Bl\n\033com" +
      ".netflix.conductor.protoB\021SkipTaskReques" +
      "tPbZ:github.com/netflix/conductor/client" +
      "/gogrpc/conductor/modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_conductor_proto_SkipTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_SkipTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_SkipTaskRequest_descriptor,
        new java.lang.String[] { "TaskInput", "TaskOutput", "TaskInputMessage", "TaskOutputMessage", });
    internal_static_conductor_proto_SkipTaskRequest_TaskInputEntry_descriptor =
      internal_static_conductor_proto_SkipTaskRequest_descriptor.getNestedTypes().get(0);
    internal_static_conductor_proto_SkipTaskRequest_TaskInputEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_SkipTaskRequest_TaskInputEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_conductor_proto_SkipTaskRequest_TaskOutputEntry_descriptor =
      internal_static_conductor_proto_SkipTaskRequest_descriptor.getNestedTypes().get(1);
    internal_static_conductor_proto_SkipTaskRequest_TaskOutputEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_SkipTaskRequest_TaskOutputEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
