// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/subworkflowparams.proto

package com.netflix.conductor.proto;

public final class SubWorkflowParamsPb {
  private SubWorkflowParamsPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubWorkflowParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.SubWorkflowParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 version = 2;</code>
     */
    int getVersion();

    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */
    int getTaskToDomainCount();
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */
    boolean containsTaskToDomain(
        java.lang.String key);
    /**
     * Use {@link #getTaskToDomainMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTaskToDomain();
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTaskToDomainMap();
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */

    java.lang.String getTaskToDomainOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */

    java.lang.String getTaskToDomainOrThrow(
        java.lang.String key);

    /**
     * <code>.google.protobuf.Value workflow_definition = 4;</code>
     */
    boolean hasWorkflowDefinition();
    /**
     * <code>.google.protobuf.Value workflow_definition = 4;</code>
     */
    com.google.protobuf.Value getWorkflowDefinition();
    /**
     * <code>.google.protobuf.Value workflow_definition = 4;</code>
     */
    com.google.protobuf.ValueOrBuilder getWorkflowDefinitionOrBuilder();
  }
  /**
   * Protobuf type {@code conductor.proto.SubWorkflowParams}
   */
  public  static final class SubWorkflowParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.SubWorkflowParams)
      SubWorkflowParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubWorkflowParams.newBuilder() to construct.
    private SubWorkflowParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubWorkflowParams() {
      name_ = "";
      version_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SubWorkflowParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                taskToDomain_ = com.google.protobuf.MapField.newMapField(
                    TaskToDomainDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              taskToDomain__ = input.readMessage(
                  TaskToDomainDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              taskToDomain_.getMutableMap().put(
                  taskToDomain__.getKey(), taskToDomain__.getValue());
              break;
            }
            case 34: {
              com.google.protobuf.Value.Builder subBuilder = null;
              if (workflowDefinition_ != null) {
                subBuilder = workflowDefinition_.toBuilder();
              }
              workflowDefinition_ = input.readMessage(com.google.protobuf.Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(workflowDefinition_);
                workflowDefinition_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.SubWorkflowParamsPb.internal_static_conductor_proto_SubWorkflowParams_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetTaskToDomain();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.SubWorkflowParamsPb.internal_static_conductor_proto_SubWorkflowParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.class, com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>int32 version = 2;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int TASK_TO_DOMAIN_FIELD_NUMBER = 3;
    private static final class TaskToDomainDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.netflix.conductor.proto.SubWorkflowParamsPb.internal_static_conductor_proto_SubWorkflowParams_TaskToDomainEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> taskToDomain_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTaskToDomain() {
      if (taskToDomain_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TaskToDomainDefaultEntryHolder.defaultEntry);
      }
      return taskToDomain_;
    }

    public int getTaskToDomainCount() {
      return internalGetTaskToDomain().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */

    public boolean containsTaskToDomain(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTaskToDomain().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTaskToDomainMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTaskToDomain() {
      return getTaskToDomainMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTaskToDomainMap() {
      return internalGetTaskToDomain().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */

    public java.lang.String getTaskToDomainOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTaskToDomain().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
     */

    public java.lang.String getTaskToDomainOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTaskToDomain().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int WORKFLOW_DEFINITION_FIELD_NUMBER = 4;
    private com.google.protobuf.Value workflowDefinition_;
    /**
     * <code>.google.protobuf.Value workflow_definition = 4;</code>
     */
    public boolean hasWorkflowDefinition() {
      return workflowDefinition_ != null;
    }
    /**
     * <code>.google.protobuf.Value workflow_definition = 4;</code>
     */
    public com.google.protobuf.Value getWorkflowDefinition() {
      return workflowDefinition_ == null ? com.google.protobuf.Value.getDefaultInstance() : workflowDefinition_;
    }
    /**
     * <code>.google.protobuf.Value workflow_definition = 4;</code>
     */
    public com.google.protobuf.ValueOrBuilder getWorkflowDefinitionOrBuilder() {
      return getWorkflowDefinition();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTaskToDomain(),
          TaskToDomainDefaultEntryHolder.defaultEntry,
          3);
      if (workflowDefinition_ != null) {
        output.writeMessage(4, getWorkflowDefinition());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTaskToDomain().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        taskToDomain__ = TaskToDomainDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, taskToDomain__);
      }
      if (workflowDefinition_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getWorkflowDefinition());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams other = (com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && (getVersion()
          == other.getVersion());
      result = result && internalGetTaskToDomain().equals(
          other.internalGetTaskToDomain());
      result = result && (hasWorkflowDefinition() == other.hasWorkflowDefinition());
      if (hasWorkflowDefinition()) {
        result = result && getWorkflowDefinition()
            .equals(other.getWorkflowDefinition());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      if (!internalGetTaskToDomain().getMap().isEmpty()) {
        hash = (37 * hash) + TASK_TO_DOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTaskToDomain().hashCode();
      }
      if (hasWorkflowDefinition()) {
        hash = (37 * hash) + WORKFLOW_DEFINITION_FIELD_NUMBER;
        hash = (53 * hash) + getWorkflowDefinition().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.SubWorkflowParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.SubWorkflowParams)
        com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.SubWorkflowParamsPb.internal_static_conductor_proto_SubWorkflowParams_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetTaskToDomain();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableTaskToDomain();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.SubWorkflowParamsPb.internal_static_conductor_proto_SubWorkflowParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.class, com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        version_ = 0;

        internalGetMutableTaskToDomain().clear();
        if (workflowDefinitionBuilder_ == null) {
          workflowDefinition_ = null;
        } else {
          workflowDefinition_ = null;
          workflowDefinitionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.SubWorkflowParamsPb.internal_static_conductor_proto_SubWorkflowParams_descriptor;
      }

      public com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams getDefaultInstanceForType() {
        return com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.getDefaultInstance();
      }

      public com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams build() {
        com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams buildPartial() {
        com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams result = new com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        result.version_ = version_;
        result.taskToDomain_ = internalGetTaskToDomain();
        result.taskToDomain_.makeImmutable();
        if (workflowDefinitionBuilder_ == null) {
          result.workflowDefinition_ = workflowDefinition_;
        } else {
          result.workflowDefinition_ = workflowDefinitionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams) {
          return mergeFrom((com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams other) {
        if (other == com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        internalGetMutableTaskToDomain().mergeFrom(
            other.internalGetTaskToDomain());
        if (other.hasWorkflowDefinition()) {
          mergeWorkflowDefinition(other.getWorkflowDefinition());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> taskToDomain_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTaskToDomain() {
        if (taskToDomain_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TaskToDomainDefaultEntryHolder.defaultEntry);
        }
        return taskToDomain_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTaskToDomain() {
        onChanged();;
        if (taskToDomain_ == null) {
          taskToDomain_ = com.google.protobuf.MapField.newMapField(
              TaskToDomainDefaultEntryHolder.defaultEntry);
        }
        if (!taskToDomain_.isMutable()) {
          taskToDomain_ = taskToDomain_.copy();
        }
        return taskToDomain_;
      }

      public int getTaskToDomainCount() {
        return internalGetTaskToDomain().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */

      public boolean containsTaskToDomain(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTaskToDomain().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTaskToDomainMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTaskToDomain() {
        return getTaskToDomainMap();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getTaskToDomainMap() {
        return internalGetTaskToDomain().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */

      public java.lang.String getTaskToDomainOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTaskToDomain().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */

      public java.lang.String getTaskToDomainOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTaskToDomain().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTaskToDomain() {
        internalGetMutableTaskToDomain().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */

      public Builder removeTaskToDomain(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskToDomain().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTaskToDomain() {
        return internalGetMutableTaskToDomain().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */
      public Builder putTaskToDomain(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskToDomain().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 3;</code>
       */

      public Builder putAllTaskToDomain(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTaskToDomain().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.Value workflowDefinition_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> workflowDefinitionBuilder_;
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public boolean hasWorkflowDefinition() {
        return workflowDefinitionBuilder_ != null || workflowDefinition_ != null;
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public com.google.protobuf.Value getWorkflowDefinition() {
        if (workflowDefinitionBuilder_ == null) {
          return workflowDefinition_ == null ? com.google.protobuf.Value.getDefaultInstance() : workflowDefinition_;
        } else {
          return workflowDefinitionBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public Builder setWorkflowDefinition(com.google.protobuf.Value value) {
        if (workflowDefinitionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          workflowDefinition_ = value;
          onChanged();
        } else {
          workflowDefinitionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public Builder setWorkflowDefinition(
          com.google.protobuf.Value.Builder builderForValue) {
        if (workflowDefinitionBuilder_ == null) {
          workflowDefinition_ = builderForValue.build();
          onChanged();
        } else {
          workflowDefinitionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public Builder mergeWorkflowDefinition(com.google.protobuf.Value value) {
        if (workflowDefinitionBuilder_ == null) {
          if (workflowDefinition_ != null) {
            workflowDefinition_ =
              com.google.protobuf.Value.newBuilder(workflowDefinition_).mergeFrom(value).buildPartial();
          } else {
            workflowDefinition_ = value;
          }
          onChanged();
        } else {
          workflowDefinitionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public Builder clearWorkflowDefinition() {
        if (workflowDefinitionBuilder_ == null) {
          workflowDefinition_ = null;
          onChanged();
        } else {
          workflowDefinition_ = null;
          workflowDefinitionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public com.google.protobuf.Value.Builder getWorkflowDefinitionBuilder() {
        
        onChanged();
        return getWorkflowDefinitionFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      public com.google.protobuf.ValueOrBuilder getWorkflowDefinitionOrBuilder() {
        if (workflowDefinitionBuilder_ != null) {
          return workflowDefinitionBuilder_.getMessageOrBuilder();
        } else {
          return workflowDefinition_ == null ?
              com.google.protobuf.Value.getDefaultInstance() : workflowDefinition_;
        }
      }
      /**
       * <code>.google.protobuf.Value workflow_definition = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder> 
          getWorkflowDefinitionFieldBuilder() {
        if (workflowDefinitionBuilder_ == null) {
          workflowDefinitionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Value, com.google.protobuf.Value.Builder, com.google.protobuf.ValueOrBuilder>(
                  getWorkflowDefinition(),
                  getParentForChildren(),
                  isClean());
          workflowDefinition_ = null;
        }
        return workflowDefinitionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.SubWorkflowParams)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.SubWorkflowParams)
    private static final com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams();
    }

    public static com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubWorkflowParams>
        PARSER = new com.google.protobuf.AbstractParser<SubWorkflowParams>() {
      public SubWorkflowParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubWorkflowParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SubWorkflowParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubWorkflowParams> getParserForType() {
      return PARSER;
    }

    public com.netflix.conductor.proto.SubWorkflowParamsPb.SubWorkflowParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_SubWorkflowParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_SubWorkflowParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_SubWorkflowParams_TaskToDomainEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_SubWorkflowParams_TaskToDomainEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035model/subworkflowparams.proto\022\017conduct" +
      "or.proto\032\034google/protobuf/struct.proto\"\352" +
      "\001\n\021SubWorkflowParams\022\014\n\004name\030\001 \001(\t\022\017\n\007ve" +
      "rsion\030\002 \001(\005\022L\n\016task_to_domain\030\003 \003(\01324.co" +
      "nductor.proto.SubWorkflowParams.TaskToDo" +
      "mainEntry\0223\n\023workflow_definition\030\004 \001(\0132\026" +
      ".google.protobuf.Value\0323\n\021TaskToDomainEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001Bn\n\033c" +
      "om.netflix.conductor.protoB\023SubWorkflowP" +
      "aramsPbZ:github.com/netflix/conductor/cl" +
      "ient/gogrpc/conductor/modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        }, assigner);
    internal_static_conductor_proto_SubWorkflowParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_SubWorkflowParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_SubWorkflowParams_descriptor,
        new java.lang.String[] { "Name", "Version", "TaskToDomain", "WorkflowDefinition", });
    internal_static_conductor_proto_SubWorkflowParams_TaskToDomainEntry_descriptor =
      internal_static_conductor_proto_SubWorkflowParams_descriptor.getNestedTypes().get(0);
    internal_static_conductor_proto_SubWorkflowParams_TaskToDomainEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_SubWorkflowParams_TaskToDomainEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
