// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/tasksummary.proto

package com.netflix.conductor.proto;

public final class TaskSummaryPb {
  private TaskSummaryPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.TaskSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string workflow_id = 1;</code>
     */
    java.lang.String getWorkflowId();
    /**
     * <code>string workflow_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkflowIdBytes();

    /**
     * <code>string workflow_type = 2;</code>
     */
    java.lang.String getWorkflowType();
    /**
     * <code>string workflow_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getWorkflowTypeBytes();

    /**
     * <code>string correlation_id = 3;</code>
     */
    java.lang.String getCorrelationId();
    /**
     * <code>string correlation_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getCorrelationIdBytes();

    /**
     * <code>string scheduled_time = 4;</code>
     */
    java.lang.String getScheduledTime();
    /**
     * <code>string scheduled_time = 4;</code>
     */
    com.google.protobuf.ByteString
        getScheduledTimeBytes();

    /**
     * <code>string start_time = 5;</code>
     */
    java.lang.String getStartTime();
    /**
     * <code>string start_time = 5;</code>
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>string update_time = 6;</code>
     */
    java.lang.String getUpdateTime();
    /**
     * <code>string update_time = 6;</code>
     */
    com.google.protobuf.ByteString
        getUpdateTimeBytes();

    /**
     * <code>string end_time = 7;</code>
     */
    java.lang.String getEndTime();
    /**
     * <code>string end_time = 7;</code>
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    /**
     * <code>.conductor.proto.Task.Status status = 8;</code>
     */
    int getStatusValue();
    /**
     * <code>.conductor.proto.Task.Status status = 8;</code>
     */
    com.netflix.conductor.proto.TaskPb.Task.Status getStatus();

    /**
     * <code>string reason_for_incompletion = 9;</code>
     */
    java.lang.String getReasonForIncompletion();
    /**
     * <code>string reason_for_incompletion = 9;</code>
     */
    com.google.protobuf.ByteString
        getReasonForIncompletionBytes();

    /**
     * <code>int64 execution_time = 10;</code>
     */
    long getExecutionTime();

    /**
     * <code>int64 queue_wait_time = 11;</code>
     */
    long getQueueWaitTime();

    /**
     * <code>string task_def_name = 12;</code>
     */
    java.lang.String getTaskDefName();
    /**
     * <code>string task_def_name = 12;</code>
     */
    com.google.protobuf.ByteString
        getTaskDefNameBytes();

    /**
     * <code>string task_type = 13;</code>
     */
    java.lang.String getTaskType();
    /**
     * <code>string task_type = 13;</code>
     */
    com.google.protobuf.ByteString
        getTaskTypeBytes();

    /**
     * <code>string input = 14;</code>
     */
    java.lang.String getInput();
    /**
     * <code>string input = 14;</code>
     */
    com.google.protobuf.ByteString
        getInputBytes();

    /**
     * <code>string output = 15;</code>
     */
    java.lang.String getOutput();
    /**
     * <code>string output = 15;</code>
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    /**
     * <code>string task_id = 16;</code>
     */
    java.lang.String getTaskId();
    /**
     * <code>string task_id = 16;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>string external_input_payload_storage_path = 17;</code>
     */
    java.lang.String getExternalInputPayloadStoragePath();
    /**
     * <code>string external_input_payload_storage_path = 17;</code>
     */
    com.google.protobuf.ByteString
        getExternalInputPayloadStoragePathBytes();

    /**
     * <code>string external_output_payload_storage_path = 18;</code>
     */
    java.lang.String getExternalOutputPayloadStoragePath();
    /**
     * <code>string external_output_payload_storage_path = 18;</code>
     */
    com.google.protobuf.ByteString
        getExternalOutputPayloadStoragePathBytes();

    /**
     * <code>int32 workflow_priority = 19;</code>
     */
    int getWorkflowPriority();
  }
  /**
   * Protobuf type {@code conductor.proto.TaskSummary}
   */
  public  static final class TaskSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.TaskSummary)
      TaskSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskSummary.newBuilder() to construct.
    private TaskSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskSummary() {
      workflowId_ = "";
      workflowType_ = "";
      correlationId_ = "";
      scheduledTime_ = "";
      startTime_ = "";
      updateTime_ = "";
      endTime_ = "";
      status_ = 0;
      reasonForIncompletion_ = "";
      executionTime_ = 0L;
      queueWaitTime_ = 0L;
      taskDefName_ = "";
      taskType_ = "";
      input_ = "";
      output_ = "";
      taskId_ = "";
      externalInputPayloadStoragePath_ = "";
      externalOutputPayloadStoragePath_ = "";
      workflowPriority_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workflowId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              workflowType_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              correlationId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              scheduledTime_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              startTime_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              updateTime_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              endTime_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              reasonForIncompletion_ = s;
              break;
            }
            case 80: {

              executionTime_ = input.readInt64();
              break;
            }
            case 88: {

              queueWaitTime_ = input.readInt64();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              taskDefName_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              taskType_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              input_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              output_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 138: {
              java.lang.String s = input.readStringRequireUtf8();

              externalInputPayloadStoragePath_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              externalOutputPayloadStoragePath_ = s;
              break;
            }
            case 152: {

              workflowPriority_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.TaskSummaryPb.internal_static_conductor_proto_TaskSummary_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.TaskSummaryPb.internal_static_conductor_proto_TaskSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.class, com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.Builder.class);
    }

    public static final int WORKFLOW_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workflowId_;
    /**
     * <code>string workflow_id = 1;</code>
     */
    public java.lang.String getWorkflowId() {
      java.lang.Object ref = workflowId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowId_ = s;
        return s;
      }
    }
    /**
     * <code>string workflow_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkflowIdBytes() {
      java.lang.Object ref = workflowId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKFLOW_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object workflowType_;
    /**
     * <code>string workflow_type = 2;</code>
     */
    public java.lang.String getWorkflowType() {
      java.lang.Object ref = workflowType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowType_ = s;
        return s;
      }
    }
    /**
     * <code>string workflow_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getWorkflowTypeBytes() {
      java.lang.Object ref = workflowType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORRELATION_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object correlationId_;
    /**
     * <code>string correlation_id = 3;</code>
     */
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      }
    }
    /**
     * <code>string correlation_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCHEDULED_TIME_FIELD_NUMBER = 4;
    private volatile java.lang.Object scheduledTime_;
    /**
     * <code>string scheduled_time = 4;</code>
     */
    public java.lang.String getScheduledTime() {
      java.lang.Object ref = scheduledTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scheduledTime_ = s;
        return s;
      }
    }
    /**
     * <code>string scheduled_time = 4;</code>
     */
    public com.google.protobuf.ByteString
        getScheduledTimeBytes() {
      java.lang.Object ref = scheduledTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scheduledTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object startTime_;
    /**
     * <code>string start_time = 5;</code>
     */
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      }
    }
    /**
     * <code>string start_time = 5;</code>
     */
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATE_TIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object updateTime_;
    /**
     * <code>string update_time = 6;</code>
     */
    public java.lang.String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string update_time = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int END_TIME_FIELD_NUMBER = 7;
    private volatile java.lang.Object endTime_;
    /**
     * <code>string end_time = 7;</code>
     */
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      }
    }
    /**
     * <code>string end_time = 7;</code>
     */
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>.conductor.proto.Task.Status status = 8;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.conductor.proto.Task.Status status = 8;</code>
     */
    public com.netflix.conductor.proto.TaskPb.Task.Status getStatus() {
      com.netflix.conductor.proto.TaskPb.Task.Status result = com.netflix.conductor.proto.TaskPb.Task.Status.valueOf(status_);
      return result == null ? com.netflix.conductor.proto.TaskPb.Task.Status.UNRECOGNIZED : result;
    }

    public static final int REASON_FOR_INCOMPLETION_FIELD_NUMBER = 9;
    private volatile java.lang.Object reasonForIncompletion_;
    /**
     * <code>string reason_for_incompletion = 9;</code>
     */
    public java.lang.String getReasonForIncompletion() {
      java.lang.Object ref = reasonForIncompletion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reasonForIncompletion_ = s;
        return s;
      }
    }
    /**
     * <code>string reason_for_incompletion = 9;</code>
     */
    public com.google.protobuf.ByteString
        getReasonForIncompletionBytes() {
      java.lang.Object ref = reasonForIncompletion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reasonForIncompletion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXECUTION_TIME_FIELD_NUMBER = 10;
    private long executionTime_;
    /**
     * <code>int64 execution_time = 10;</code>
     */
    public long getExecutionTime() {
      return executionTime_;
    }

    public static final int QUEUE_WAIT_TIME_FIELD_NUMBER = 11;
    private long queueWaitTime_;
    /**
     * <code>int64 queue_wait_time = 11;</code>
     */
    public long getQueueWaitTime() {
      return queueWaitTime_;
    }

    public static final int TASK_DEF_NAME_FIELD_NUMBER = 12;
    private volatile java.lang.Object taskDefName_;
    /**
     * <code>string task_def_name = 12;</code>
     */
    public java.lang.String getTaskDefName() {
      java.lang.Object ref = taskDefName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskDefName_ = s;
        return s;
      }
    }
    /**
     * <code>string task_def_name = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTaskDefNameBytes() {
      java.lang.Object ref = taskDefName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskDefName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_TYPE_FIELD_NUMBER = 13;
    private volatile java.lang.Object taskType_;
    /**
     * <code>string task_type = 13;</code>
     */
    public java.lang.String getTaskType() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskType_ = s;
        return s;
      }
    }
    /**
     * <code>string task_type = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTypeBytes() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 14;
    private volatile java.lang.Object input_;
    /**
     * <code>string input = 14;</code>
     */
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        input_ = s;
        return s;
      }
    }
    /**
     * <code>string input = 14;</code>
     */
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUT_FIELD_NUMBER = 15;
    private volatile java.lang.Object output_;
    /**
     * <code>string output = 15;</code>
     */
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      }
    }
    /**
     * <code>string output = 15;</code>
     */
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_ID_FIELD_NUMBER = 16;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string task_id = 16;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string task_id = 16;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNAL_INPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER = 17;
    private volatile java.lang.Object externalInputPayloadStoragePath_;
    /**
     * <code>string external_input_payload_storage_path = 17;</code>
     */
    public java.lang.String getExternalInputPayloadStoragePath() {
      java.lang.Object ref = externalInputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalInputPayloadStoragePath_ = s;
        return s;
      }
    }
    /**
     * <code>string external_input_payload_storage_path = 17;</code>
     */
    public com.google.protobuf.ByteString
        getExternalInputPayloadStoragePathBytes() {
      java.lang.Object ref = externalInputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalInputPayloadStoragePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNAL_OUTPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER = 18;
    private volatile java.lang.Object externalOutputPayloadStoragePath_;
    /**
     * <code>string external_output_payload_storage_path = 18;</code>
     */
    public java.lang.String getExternalOutputPayloadStoragePath() {
      java.lang.Object ref = externalOutputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalOutputPayloadStoragePath_ = s;
        return s;
      }
    }
    /**
     * <code>string external_output_payload_storage_path = 18;</code>
     */
    public com.google.protobuf.ByteString
        getExternalOutputPayloadStoragePathBytes() {
      java.lang.Object ref = externalOutputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalOutputPayloadStoragePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKFLOW_PRIORITY_FIELD_NUMBER = 19;
    private int workflowPriority_;
    /**
     * <code>int32 workflow_priority = 19;</code>
     */
    public int getWorkflowPriority() {
      return workflowPriority_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkflowIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workflowId_);
      }
      if (!getWorkflowTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, workflowType_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, correlationId_);
      }
      if (!getScheduledTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, scheduledTime_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, updateTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, endTime_);
      }
      if (status_ != com.netflix.conductor.proto.TaskPb.Task.Status.IN_PROGRESS.getNumber()) {
        output.writeEnum(8, status_);
      }
      if (!getReasonForIncompletionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, reasonForIncompletion_);
      }
      if (executionTime_ != 0L) {
        output.writeInt64(10, executionTime_);
      }
      if (queueWaitTime_ != 0L) {
        output.writeInt64(11, queueWaitTime_);
      }
      if (!getTaskDefNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, taskDefName_);
      }
      if (!getTaskTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, taskType_);
      }
      if (!getInputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, input_);
      }
      if (!getOutputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, output_);
      }
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, taskId_);
      }
      if (!getExternalInputPayloadStoragePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 17, externalInputPayloadStoragePath_);
      }
      if (!getExternalOutputPayloadStoragePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, externalOutputPayloadStoragePath_);
      }
      if (workflowPriority_ != 0) {
        output.writeInt32(19, workflowPriority_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkflowIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workflowId_);
      }
      if (!getWorkflowTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, workflowType_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, correlationId_);
      }
      if (!getScheduledTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, scheduledTime_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, startTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, updateTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, endTime_);
      }
      if (status_ != com.netflix.conductor.proto.TaskPb.Task.Status.IN_PROGRESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, status_);
      }
      if (!getReasonForIncompletionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, reasonForIncompletion_);
      }
      if (executionTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, executionTime_);
      }
      if (queueWaitTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, queueWaitTime_);
      }
      if (!getTaskDefNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, taskDefName_);
      }
      if (!getTaskTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, taskType_);
      }
      if (!getInputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, input_);
      }
      if (!getOutputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, output_);
      }
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, taskId_);
      }
      if (!getExternalInputPayloadStoragePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, externalInputPayloadStoragePath_);
      }
      if (!getExternalOutputPayloadStoragePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, externalOutputPayloadStoragePath_);
      }
      if (workflowPriority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, workflowPriority_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.TaskSummaryPb.TaskSummary)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.TaskSummaryPb.TaskSummary other = (com.netflix.conductor.proto.TaskSummaryPb.TaskSummary) obj;

      boolean result = true;
      result = result && getWorkflowId()
          .equals(other.getWorkflowId());
      result = result && getWorkflowType()
          .equals(other.getWorkflowType());
      result = result && getCorrelationId()
          .equals(other.getCorrelationId());
      result = result && getScheduledTime()
          .equals(other.getScheduledTime());
      result = result && getStartTime()
          .equals(other.getStartTime());
      result = result && getUpdateTime()
          .equals(other.getUpdateTime());
      result = result && getEndTime()
          .equals(other.getEndTime());
      result = result && status_ == other.status_;
      result = result && getReasonForIncompletion()
          .equals(other.getReasonForIncompletion());
      result = result && (getExecutionTime()
          == other.getExecutionTime());
      result = result && (getQueueWaitTime()
          == other.getQueueWaitTime());
      result = result && getTaskDefName()
          .equals(other.getTaskDefName());
      result = result && getTaskType()
          .equals(other.getTaskType());
      result = result && getInput()
          .equals(other.getInput());
      result = result && getOutput()
          .equals(other.getOutput());
      result = result && getTaskId()
          .equals(other.getTaskId());
      result = result && getExternalInputPayloadStoragePath()
          .equals(other.getExternalInputPayloadStoragePath());
      result = result && getExternalOutputPayloadStoragePath()
          .equals(other.getExternalOutputPayloadStoragePath());
      result = result && (getWorkflowPriority()
          == other.getWorkflowPriority());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKFLOW_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowId().hashCode();
      hash = (37 * hash) + WORKFLOW_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowType().hashCode();
      hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCorrelationId().hashCode();
      hash = (37 * hash) + SCHEDULED_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getScheduledTime().hashCode();
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
      hash = (37 * hash) + END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + REASON_FOR_INCOMPLETION_FIELD_NUMBER;
      hash = (53 * hash) + getReasonForIncompletion().hashCode();
      hash = (37 * hash) + EXECUTION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecutionTime());
      hash = (37 * hash) + QUEUE_WAIT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getQueueWaitTime());
      hash = (37 * hash) + TASK_DEF_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTaskDefName().hashCode();
      hash = (37 * hash) + TASK_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getTaskType().hashCode();
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + EXTERNAL_INPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getExternalInputPayloadStoragePath().hashCode();
      hash = (37 * hash) + EXTERNAL_OUTPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getExternalOutputPayloadStoragePath().hashCode();
      hash = (37 * hash) + WORKFLOW_PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowPriority();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.TaskSummaryPb.TaskSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.TaskSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.TaskSummary)
        com.netflix.conductor.proto.TaskSummaryPb.TaskSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.TaskSummaryPb.internal_static_conductor_proto_TaskSummary_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.TaskSummaryPb.internal_static_conductor_proto_TaskSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.class, com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        workflowId_ = "";

        workflowType_ = "";

        correlationId_ = "";

        scheduledTime_ = "";

        startTime_ = "";

        updateTime_ = "";

        endTime_ = "";

        status_ = 0;

        reasonForIncompletion_ = "";

        executionTime_ = 0L;

        queueWaitTime_ = 0L;

        taskDefName_ = "";

        taskType_ = "";

        input_ = "";

        output_ = "";

        taskId_ = "";

        externalInputPayloadStoragePath_ = "";

        externalOutputPayloadStoragePath_ = "";

        workflowPriority_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.TaskSummaryPb.internal_static_conductor_proto_TaskSummary_descriptor;
      }

      public com.netflix.conductor.proto.TaskSummaryPb.TaskSummary getDefaultInstanceForType() {
        return com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.getDefaultInstance();
      }

      public com.netflix.conductor.proto.TaskSummaryPb.TaskSummary build() {
        com.netflix.conductor.proto.TaskSummaryPb.TaskSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.netflix.conductor.proto.TaskSummaryPb.TaskSummary buildPartial() {
        com.netflix.conductor.proto.TaskSummaryPb.TaskSummary result = new com.netflix.conductor.proto.TaskSummaryPb.TaskSummary(this);
        result.workflowId_ = workflowId_;
        result.workflowType_ = workflowType_;
        result.correlationId_ = correlationId_;
        result.scheduledTime_ = scheduledTime_;
        result.startTime_ = startTime_;
        result.updateTime_ = updateTime_;
        result.endTime_ = endTime_;
        result.status_ = status_;
        result.reasonForIncompletion_ = reasonForIncompletion_;
        result.executionTime_ = executionTime_;
        result.queueWaitTime_ = queueWaitTime_;
        result.taskDefName_ = taskDefName_;
        result.taskType_ = taskType_;
        result.input_ = input_;
        result.output_ = output_;
        result.taskId_ = taskId_;
        result.externalInputPayloadStoragePath_ = externalInputPayloadStoragePath_;
        result.externalOutputPayloadStoragePath_ = externalOutputPayloadStoragePath_;
        result.workflowPriority_ = workflowPriority_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.TaskSummaryPb.TaskSummary) {
          return mergeFrom((com.netflix.conductor.proto.TaskSummaryPb.TaskSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.TaskSummaryPb.TaskSummary other) {
        if (other == com.netflix.conductor.proto.TaskSummaryPb.TaskSummary.getDefaultInstance()) return this;
        if (!other.getWorkflowId().isEmpty()) {
          workflowId_ = other.workflowId_;
          onChanged();
        }
        if (!other.getWorkflowType().isEmpty()) {
          workflowType_ = other.workflowType_;
          onChanged();
        }
        if (!other.getCorrelationId().isEmpty()) {
          correlationId_ = other.correlationId_;
          onChanged();
        }
        if (!other.getScheduledTime().isEmpty()) {
          scheduledTime_ = other.scheduledTime_;
          onChanged();
        }
        if (!other.getStartTime().isEmpty()) {
          startTime_ = other.startTime_;
          onChanged();
        }
        if (!other.getUpdateTime().isEmpty()) {
          updateTime_ = other.updateTime_;
          onChanged();
        }
        if (!other.getEndTime().isEmpty()) {
          endTime_ = other.endTime_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getReasonForIncompletion().isEmpty()) {
          reasonForIncompletion_ = other.reasonForIncompletion_;
          onChanged();
        }
        if (other.getExecutionTime() != 0L) {
          setExecutionTime(other.getExecutionTime());
        }
        if (other.getQueueWaitTime() != 0L) {
          setQueueWaitTime(other.getQueueWaitTime());
        }
        if (!other.getTaskDefName().isEmpty()) {
          taskDefName_ = other.taskDefName_;
          onChanged();
        }
        if (!other.getTaskType().isEmpty()) {
          taskType_ = other.taskType_;
          onChanged();
        }
        if (!other.getInput().isEmpty()) {
          input_ = other.input_;
          onChanged();
        }
        if (!other.getOutput().isEmpty()) {
          output_ = other.output_;
          onChanged();
        }
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getExternalInputPayloadStoragePath().isEmpty()) {
          externalInputPayloadStoragePath_ = other.externalInputPayloadStoragePath_;
          onChanged();
        }
        if (!other.getExternalOutputPayloadStoragePath().isEmpty()) {
          externalOutputPayloadStoragePath_ = other.externalOutputPayloadStoragePath_;
          onChanged();
        }
        if (other.getWorkflowPriority() != 0) {
          setWorkflowPriority(other.getWorkflowPriority());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.TaskSummaryPb.TaskSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.TaskSummaryPb.TaskSummary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workflowId_ = "";
      /**
       * <code>string workflow_id = 1;</code>
       */
      public java.lang.String getWorkflowId() {
        java.lang.Object ref = workflowId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workflowId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workflow_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkflowIdBytes() {
        java.lang.Object ref = workflowId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workflowId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workflow_id = 1;</code>
       */
      public Builder setWorkflowId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workflowId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_id = 1;</code>
       */
      public Builder clearWorkflowId() {
        
        workflowId_ = getDefaultInstance().getWorkflowId();
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_id = 1;</code>
       */
      public Builder setWorkflowIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workflowId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object workflowType_ = "";
      /**
       * <code>string workflow_type = 2;</code>
       */
      public java.lang.String getWorkflowType() {
        java.lang.Object ref = workflowType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workflowType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workflow_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getWorkflowTypeBytes() {
        java.lang.Object ref = workflowType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workflowType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workflow_type = 2;</code>
       */
      public Builder setWorkflowType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workflowType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_type = 2;</code>
       */
      public Builder clearWorkflowType() {
        
        workflowType_ = getDefaultInstance().getWorkflowType();
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_type = 2;</code>
       */
      public Builder setWorkflowTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workflowType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object correlationId_ = "";
      /**
       * <code>string correlation_id = 3;</code>
       */
      public java.lang.String getCorrelationId() {
        java.lang.Object ref = correlationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          correlationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string correlation_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCorrelationIdBytes() {
        java.lang.Object ref = correlationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correlationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string correlation_id = 3;</code>
       */
      public Builder setCorrelationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        correlationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 3;</code>
       */
      public Builder clearCorrelationId() {
        
        correlationId_ = getDefaultInstance().getCorrelationId();
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 3;</code>
       */
      public Builder setCorrelationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        correlationId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scheduledTime_ = "";
      /**
       * <code>string scheduled_time = 4;</code>
       */
      public java.lang.String getScheduledTime() {
        java.lang.Object ref = scheduledTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          scheduledTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string scheduled_time = 4;</code>
       */
      public com.google.protobuf.ByteString
          getScheduledTimeBytes() {
        java.lang.Object ref = scheduledTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scheduledTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string scheduled_time = 4;</code>
       */
      public Builder setScheduledTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        scheduledTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string scheduled_time = 4;</code>
       */
      public Builder clearScheduledTime() {
        
        scheduledTime_ = getDefaultInstance().getScheduledTime();
        onChanged();
        return this;
      }
      /**
       * <code>string scheduled_time = 4;</code>
       */
      public Builder setScheduledTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        scheduledTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <code>string start_time = 5;</code>
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string start_time = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string start_time = 5;</code>
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string start_time = 5;</code>
       */
      public Builder clearStartTime() {
        
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>string start_time = 5;</code>
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object updateTime_ = "";
      /**
       * <code>string update_time = 6;</code>
       */
      public java.lang.String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string update_time = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUpdateTimeBytes() {
        java.lang.Object ref = updateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string update_time = 6;</code>
       */
      public Builder setUpdateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string update_time = 6;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string update_time = 6;</code>
       */
      public Builder setUpdateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endTime_ = "";
      /**
       * <code>string end_time = 7;</code>
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string end_time = 7;</code>
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string end_time = 7;</code>
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string end_time = 7;</code>
       */
      public Builder clearEndTime() {
        
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>string end_time = 7;</code>
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endTime_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.conductor.proto.Task.Status status = 8;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.conductor.proto.Task.Status status = 8;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.Task.Status status = 8;</code>
       */
      public com.netflix.conductor.proto.TaskPb.Task.Status getStatus() {
        com.netflix.conductor.proto.TaskPb.Task.Status result = com.netflix.conductor.proto.TaskPb.Task.Status.valueOf(status_);
        return result == null ? com.netflix.conductor.proto.TaskPb.Task.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.conductor.proto.Task.Status status = 8;</code>
       */
      public Builder setStatus(com.netflix.conductor.proto.TaskPb.Task.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.Task.Status status = 8;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object reasonForIncompletion_ = "";
      /**
       * <code>string reason_for_incompletion = 9;</code>
       */
      public java.lang.String getReasonForIncompletion() {
        java.lang.Object ref = reasonForIncompletion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reasonForIncompletion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reason_for_incompletion = 9;</code>
       */
      public com.google.protobuf.ByteString
          getReasonForIncompletionBytes() {
        java.lang.Object ref = reasonForIncompletion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reasonForIncompletion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reason_for_incompletion = 9;</code>
       */
      public Builder setReasonForIncompletion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reasonForIncompletion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reason_for_incompletion = 9;</code>
       */
      public Builder clearReasonForIncompletion() {
        
        reasonForIncompletion_ = getDefaultInstance().getReasonForIncompletion();
        onChanged();
        return this;
      }
      /**
       * <code>string reason_for_incompletion = 9;</code>
       */
      public Builder setReasonForIncompletionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reasonForIncompletion_ = value;
        onChanged();
        return this;
      }

      private long executionTime_ ;
      /**
       * <code>int64 execution_time = 10;</code>
       */
      public long getExecutionTime() {
        return executionTime_;
      }
      /**
       * <code>int64 execution_time = 10;</code>
       */
      public Builder setExecutionTime(long value) {
        
        executionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 execution_time = 10;</code>
       */
      public Builder clearExecutionTime() {
        
        executionTime_ = 0L;
        onChanged();
        return this;
      }

      private long queueWaitTime_ ;
      /**
       * <code>int64 queue_wait_time = 11;</code>
       */
      public long getQueueWaitTime() {
        return queueWaitTime_;
      }
      /**
       * <code>int64 queue_wait_time = 11;</code>
       */
      public Builder setQueueWaitTime(long value) {
        
        queueWaitTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 queue_wait_time = 11;</code>
       */
      public Builder clearQueueWaitTime() {
        
        queueWaitTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object taskDefName_ = "";
      /**
       * <code>string task_def_name = 12;</code>
       */
      public java.lang.String getTaskDefName() {
        java.lang.Object ref = taskDefName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskDefName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string task_def_name = 12;</code>
       */
      public com.google.protobuf.ByteString
          getTaskDefNameBytes() {
        java.lang.Object ref = taskDefName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskDefName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string task_def_name = 12;</code>
       */
      public Builder setTaskDefName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskDefName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string task_def_name = 12;</code>
       */
      public Builder clearTaskDefName() {
        
        taskDefName_ = getDefaultInstance().getTaskDefName();
        onChanged();
        return this;
      }
      /**
       * <code>string task_def_name = 12;</code>
       */
      public Builder setTaskDefNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskDefName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskType_ = "";
      /**
       * <code>string task_type = 13;</code>
       */
      public java.lang.String getTaskType() {
        java.lang.Object ref = taskType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string task_type = 13;</code>
       */
      public com.google.protobuf.ByteString
          getTaskTypeBytes() {
        java.lang.Object ref = taskType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string task_type = 13;</code>
       */
      public Builder setTaskType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string task_type = 13;</code>
       */
      public Builder clearTaskType() {
        
        taskType_ = getDefaultInstance().getTaskType();
        onChanged();
        return this;
      }
      /**
       * <code>string task_type = 13;</code>
       */
      public Builder setTaskTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object input_ = "";
      /**
       * <code>string input = 14;</code>
       */
      public java.lang.String getInput() {
        java.lang.Object ref = input_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          input_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string input = 14;</code>
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        java.lang.Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string input = 14;</code>
       */
      public Builder setInput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string input = 14;</code>
       */
      public Builder clearInput() {
        
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>string input = 14;</code>
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        input_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object output_ = "";
      /**
       * <code>string output = 15;</code>
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          output_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string output = 15;</code>
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string output = 15;</code>
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string output = 15;</code>
       */
      public Builder clearOutput() {
        
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <code>string output = 15;</code>
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        output_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <code>string task_id = 16;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string task_id = 16;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string task_id = 16;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string task_id = 16;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string task_id = 16;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalInputPayloadStoragePath_ = "";
      /**
       * <code>string external_input_payload_storage_path = 17;</code>
       */
      public java.lang.String getExternalInputPayloadStoragePath() {
        java.lang.Object ref = externalInputPayloadStoragePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalInputPayloadStoragePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_input_payload_storage_path = 17;</code>
       */
      public com.google.protobuf.ByteString
          getExternalInputPayloadStoragePathBytes() {
        java.lang.Object ref = externalInputPayloadStoragePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalInputPayloadStoragePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_input_payload_storage_path = 17;</code>
       */
      public Builder setExternalInputPayloadStoragePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalInputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_input_payload_storage_path = 17;</code>
       */
      public Builder clearExternalInputPayloadStoragePath() {
        
        externalInputPayloadStoragePath_ = getDefaultInstance().getExternalInputPayloadStoragePath();
        onChanged();
        return this;
      }
      /**
       * <code>string external_input_payload_storage_path = 17;</code>
       */
      public Builder setExternalInputPayloadStoragePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalInputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalOutputPayloadStoragePath_ = "";
      /**
       * <code>string external_output_payload_storage_path = 18;</code>
       */
      public java.lang.String getExternalOutputPayloadStoragePath() {
        java.lang.Object ref = externalOutputPayloadStoragePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalOutputPayloadStoragePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_output_payload_storage_path = 18;</code>
       */
      public com.google.protobuf.ByteString
          getExternalOutputPayloadStoragePathBytes() {
        java.lang.Object ref = externalOutputPayloadStoragePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalOutputPayloadStoragePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_output_payload_storage_path = 18;</code>
       */
      public Builder setExternalOutputPayloadStoragePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalOutputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_output_payload_storage_path = 18;</code>
       */
      public Builder clearExternalOutputPayloadStoragePath() {
        
        externalOutputPayloadStoragePath_ = getDefaultInstance().getExternalOutputPayloadStoragePath();
        onChanged();
        return this;
      }
      /**
       * <code>string external_output_payload_storage_path = 18;</code>
       */
      public Builder setExternalOutputPayloadStoragePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalOutputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }

      private int workflowPriority_ ;
      /**
       * <code>int32 workflow_priority = 19;</code>
       */
      public int getWorkflowPriority() {
        return workflowPriority_;
      }
      /**
       * <code>int32 workflow_priority = 19;</code>
       */
      public Builder setWorkflowPriority(int value) {
        
        workflowPriority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 workflow_priority = 19;</code>
       */
      public Builder clearWorkflowPriority() {
        
        workflowPriority_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.TaskSummary)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.TaskSummary)
    private static final com.netflix.conductor.proto.TaskSummaryPb.TaskSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.TaskSummaryPb.TaskSummary();
    }

    public static com.netflix.conductor.proto.TaskSummaryPb.TaskSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskSummary>
        PARSER = new com.google.protobuf.AbstractParser<TaskSummary>() {
      public TaskSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskSummary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskSummary> getParserForType() {
      return PARSER;
    }

    public com.netflix.conductor.proto.TaskSummaryPb.TaskSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_TaskSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_TaskSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027model/tasksummary.proto\022\017conductor.pro" +
      "to\032\020model/task.proto\"\364\003\n\013TaskSummary\022\023\n\013" +
      "workflow_id\030\001 \001(\t\022\025\n\rworkflow_type\030\002 \001(\t" +
      "\022\026\n\016correlation_id\030\003 \001(\t\022\026\n\016scheduled_ti" +
      "me\030\004 \001(\t\022\022\n\nstart_time\030\005 \001(\t\022\023\n\013update_t" +
      "ime\030\006 \001(\t\022\020\n\010end_time\030\007 \001(\t\022,\n\006status\030\010 " +
      "\001(\0162\034.conductor.proto.Task.Status\022\037\n\027rea" +
      "son_for_incompletion\030\t \001(\t\022\026\n\016execution_" +
      "time\030\n \001(\003\022\027\n\017queue_wait_time\030\013 \001(\003\022\025\n\rt" +
      "ask_def_name\030\014 \001(\t\022\021\n\ttask_type\030\r \001(\t\022\r\n" +
      "\005input\030\016 \001(\t\022\016\n\006output\030\017 \001(\t\022\017\n\007task_id\030" +
      "\020 \001(\t\022+\n#external_input_payload_storage_" +
      "path\030\021 \001(\t\022,\n$external_output_payload_st" +
      "orage_path\030\022 \001(\t\022\031\n\021workflow_priority\030\023 " +
      "\001(\005Bh\n\033com.netflix.conductor.protoB\rTask" +
      "SummaryPbZ:github.com/netflix/conductor/" +
      "client/gogrpc/conductor/modelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.netflix.conductor.proto.TaskPb.getDescriptor(),
        }, assigner);
    internal_static_conductor_proto_TaskSummary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_TaskSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_TaskSummary_descriptor,
        new java.lang.String[] { "WorkflowId", "WorkflowType", "CorrelationId", "ScheduledTime", "StartTime", "UpdateTime", "EndTime", "Status", "ReasonForIncompletion", "ExecutionTime", "QueueWaitTime", "TaskDefName", "TaskType", "Input", "Output", "TaskId", "ExternalInputPayloadStoragePath", "ExternalOutputPayloadStoragePath", "WorkflowPriority", });
    com.netflix.conductor.proto.TaskPb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
